<?php

namespace App\Http\Requests;

use App\Rules\MyRule;
use Illuminate\Foundation\Http\FormRequest;

class TestFormRequest extends FormRequest
{
                 //    по умолчанию возврат обратно, но можно поменятья
/*  protected $redirect = '/';
    protected $redirectRoute = 'index';        // редирект на: имя именнованного маршрута*/

//    protected $stopOnFirstFailure = true;    //валидация останавливается при первой ошибке

    /**
     * Determine if the user is authorized to make this request. авторизован ли пользователь проверяет
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'name' => 'required| min:2|max:100',
            'text' => 'required|max:100',
            'bd' => 'nullable|date',
            'test' => [new MyRule()] // в массиве указывать свое созданное правило
        ];
    }

    public function messages()
    {
//        return parent::messages(); // TODO: Change the autogenerated stub
        return [
            'name.required'=> ':attribute то заполните пожалуйста',
//            'name.min'=>'уж очень коротенькое имя'
        ];
    }

    public function attributes()
    {
//        return parent::attributes(); // TODO: Change the autogenerated stub// определенные имена аттрибутам
        return[
//            'text'=>'тееекст'
        ];
    }
}
